{{- if .Values.ingestionWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowledge-platform.ingestionWorker.fullname" . }}
  labels:
    app.kubernetes.io/component: ingestion-worker
    {{- include "knowledge-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ingestionWorker.service.type }}
  ports:
    - port: {{ .Values.ingestionWorker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: ingestion-worker
    {{- include "knowledge-platform.selectorLabels" . | nindent 4 }}
{{- end }}
