apiVersion: v1
entries:
  knowledge-platform:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2025-12-25T08:55:37.516293-05:00"
    dependencies:
    - condition: meilisearch.enabled
      name: meilisearch
      repository: https://meilisearch.github.io/meilisearch-kubernetes
      version: 0.19.0
    description: Deploys Knowledge Platform services (ingestion worker and MCP server)
      with a Meilisearch dependency.
    digest: 4b97825aa8d6a862a4d1b22b01880e268a0f4ab7fa8b8077d03186019f29902e
    name: knowledge-platform
    type: application
    urls:
    - https://aboogie24.github.io/knowledge-platform/charts/knowledge-platform-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-25T08:55:37.51514-05:00"
